//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NawareKulCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NawareKulCore.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A typical name is identified in any society, except in a family (except in South American customs); They are called &apos;first names&apos; or &apos;last names&apos;. Today the people of any family are almost scattered around the world; But during the history, his ancestors lived in a small area of ​​India (in a district of Konkan). From that time, on the basis of historical documents, by making history and genealogy of that family till date, by registering information about the clans in different places; The task of creating  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Kulvruttant.
        /// </summary>
        public static string AboutKulvruttantTitle {
            get {
                return ResourceManager.GetString("AboutKulvruttantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bharadwaj rushi.
        /// </summary>
        public static string Bharadwajhrushi {
            get {
                return ResourceManager.GetString("Bharadwajhrushi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naware households are counted as Bharadwaj Kunalpan at &apos;Karhade&apos; Brahmin branch. Rishi Bharadwaj is a Hindu mythology and one of the sages who are mentioned in the Vedas. He was an ashram near Dandakaranya. They were supplementary. Acharya Bhardwaj explored 600 years ago for his astronomy. Acharya Bharadwaj had done research that could fly from one planet to another, and could not even think of Western researchers such as inventing a plane flying from one universe to another, and flying the aircraft. Accord [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Bhardwaj_Desc {
            get {
                return ResourceManager.GetString("Bhardwaj_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; &lt;u&gt; “धोपेश्वर” देवस्थान हे राजापूर तालुक्या मधील धोपेश्वर खेडयातील प्रसिद्ध मंदीर आहे. &lt;/u&gt;
        ///          &amp;nbsp;धुतपापेश्वरच्या केवळ दर्शनानेच पापे धुतली जातात आणि त्यामुळेच पाप धुणारा देव म्हणून धुतपापेशवर हे देवस्थान पूर्वापार प्रसिद्ध आहे. हे शिवमंदिर फार पुरातन आहे  तथापि,१५ ते २० वर्षापूर्वी   
        ///          या मंदिराचे जिर्णोधाराचे काम पूर्वीच्या लाकडावरील कोरीवनक्षीकाम कायम ठेवून गाभार्यारच दगडी तर सभामंडपाचे लाकडी काम  नव्याने करण्यात आ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dhopeshwar_Desc {
            get {
                return ResourceManager.GetString("Dhopeshwar_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhopeshwar.
        /// </summary>
        public static string Dhupeshwar {
            get {
                return ResourceManager.GetString("Dhupeshwar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhopeshwar.
        /// </summary>
        public static string Dhupeshwar_Title {
            get {
                return ResourceManager.GetString("Dhupeshwar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string F_Education {
            get {
                return ResourceManager.GetString("F_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string F_Informatio {
            get {
                return ResourceManager.GetString("F_Informatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainWork.
        /// </summary>
        public static string F_MainWork {
            get {
                return ResourceManager.GetString("F_MainWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string F_Name {
            get {
                return ResourceManager.GetString("F_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string F_Work {
            get {
                return ResourceManager.GetString("F_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyTree.
        /// </summary>
        public static string FamilyTree {
            get {
                return ResourceManager.GetString("FamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famous people in Naware Family.
        /// </summary>
        public static string FamousPeople {
            get {
                return ResourceManager.GetString("FamousPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famous Persons.
        /// </summary>
        public static string FamousPersons {
            get {
                return ResourceManager.GetString("FamousPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naware People.
        /// </summary>
        public static string NawarePeople {
            get {
                return ResourceManager.GetString("NawarePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Form.
        /// </summary>
        public static string OnlineForm {
            get {
                return ResourceManager.GetString("OnlineForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prastavna.
        /// </summary>
        public static string Prastavna {
            get {
                return ResourceManager.GetString("Prastavna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The concept of &apos;Kulavruttanta&apos; means &apos;Family tree&apos; existed in all previous generations (since the discovery of diagnostic printing techniques) existed. The recent findings of print-art as it has been in the past 300-400 years ago. Earlier, there were reports of ancient civilizations such as Indian, Chinese, Egyptian, in many places like copper, stone, on the wall, because it is obvious - the medium used to be available was then used. Due to the absence of any medium since ancient times, the Vedas were prese [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Prastavna_Description {
            get {
                return ResourceManager.GetString("Prastavna_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        public static string UserGuide {
            get {
                return ResourceManager.GetString("UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Naware Kulvruttant Website.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
